### ISSUE TITLE
 Add GitHub Actions Workflow to Run Tests Automatically

### ISSUE THREAD

**Issue by AbsoluteZero000** [envicutor/envicutor#1]
I will be creating GitHub Actions to automate the testing process for this project.

### Tasks:

- [x] Create a GitHub Actions workflow file.
- [x] Configure the workflow to run tests.
- [x] Ensure that the workflow triggers on push and pull request events.

if you have any suggestions let me know
